[book]
authors = ["Yuchen Mu"]
language = "en"
multilingual = false
src = "src"
title = "uCore on risc-v"
description = "2023年南开大学操作系统实验指北"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/TephrocactusMYC/uCoreOnRiscvDiy"
git-repository-icon = "fa-github"
[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.markdown]
